version: '3.7'
services:
    producer:
        image: rabbit-flow
        build:
          context: ./python/
        labels:
          NAME: "producer"
        command: python -u timed_producer.py rabbit1 5672 hello
        networks:
          - rabbit
    worker:
        image: rabbit-flow
        build:
          context: ./python/
        labels:
          NAME: "worker"
        command: python -u worker.py rabbit1 5672 hello
        networks:
          - rabbit
    rabbit1:
        image: rabbitmq:3-management
        container_name: rabbit1
        hostname: "rabbit1"
        environment:
          RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
          RABBITMQ_DEFAULT_USER: "rabbitmq"
          RABBITMQ_DEFAULT_PASS: "rabbitmq"
          RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - "15672:15672"
            - "5672:5672"
        labels:
          NAME: "rabbitmq1"
        networks:
           - rabbit
networks:
    rabbit:
      driver: bridge
