apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-deployment
  namespace: rabbit-ns
spec:
  selector:
    matchLabels:
      app: rabbit1
  replicas: 1
  template:
    metadata:
     labels:
      app: rabbit1
      env: test
    spec:
      containers:
      - name: rabbit-consumer
        image: rabbit-flow
        imagePullPolicy: Never
        command:
        - python
        - -u
        - consumer.py
        - localhost